[package]
name = "dsi-bitstream"
version = "0.1.0"
edition = "2021"
authors = ["Tommaso Fontana", "Sebastiano Vigna <sebastiano.vigna@unimi.it>"]

[dependencies]
anyhow = { version = "1.0.71", default-features = false }

[features]
default = ["std"]
std = ["alloc", "anyhow/std"]
alloc = []