[package]
name = "dsi-bitstream"
version = "0.1.0"
edition = "2021"
description = "A Rust implementation of read/write bit streams supporting several types of instantaneous codes"
repository = "https://github.com/vigna/dsi-bitstream-rs/"
license = "Apache-2.0 OR LGPL-2.1-or-later"
readme = "README.md"
keywords = ["bitstream", "codes", "compression"]
categories = ["compression"]
authors = ["Tommaso Fontana", "Sebastiano Vigna <sebastiano.vigna@unimi.it>"]

[dependencies]
anyhow = { version = "1.0.71", default-features = false, features = ["backtrace"] }
rand = { version = "0.8.5", features = ["small_rng"] }
arbitrary = { version = "1", features = ["derive"], optional = true }
zip = {version="0.6.6", optional=true}
common_traits = "0.7.6"

[features]
default = ["std"]
std = ["alloc", "anyhow/std"]
alloc = []
fuzz = ["dep:arbitrary", "dep:zip"]
