[package]
name = "benchmarks"
version = "0.2.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
random = "0.13.2"
dsi-bitstream = { path="../" }
rand_distr = "0.4.3"
once_cell = "1.19.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2.141"

[features]
rtdsc = []
reads = []
u16 = []
u32 = []
u64 = []
delta_gamma = []

[profile.release]
opt-level = 3             # like --release
lto = "fat"               # Full LTO
overflow-checks = false   # Disable integer overflow checks.
debug = false             # Include debug info.
debug-assertions = false  # Enables debug assertions.
codegen-units=1           # slower compile times, but maybe better perf
