name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Clippy and fmt
      run: rustup toolchain install nightly --component clippy fmt
    - name: Add baremetal x86_64 target
      run: rustup target add x86_64-unknown-none
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --target x86_64-unknown-linux-gnu
    - name: Run tests on alloc
      run: cargo test --verbose --target x86_64-unknown-linux-gnu --no-default-features --features alloc
    - name: Run tests on no_std
      run: cargo test --verbose --target x86_64-unknown-none --no-default-features
    - name: Run clippy
      run: cargo clippy -- -Dclippy::all -Dclippy::cargo